/**
 * P2-b — rewriting only the marked block leaves old dead links in place.
 *
 * The rule sections generated by `RULE_TEMPLATES` sit OUTSIDE the UDS markers,
 * and `writeIntegrationFile` replaces only what is inside them. So a file first
 * written by an older CLI keeps its `.standards/commit-message-guide.md` and
 * `.standards/anti-hallucination.md` lines for ever — which is what the adopter
 * saw after upgrading to 6.9.0, and what a second `--integrations-only` run on
 * the fixed generator still left behind (measured 2026-09-16).
 */
import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdirSync, rmSync, writeFileSync, readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { writeIntegrationFile } from '../../../src/utils/integration-generator.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const TEST_DIR = join(__dirname, '../../temp/integration-refs-existing');

const config = {
  categories: ['anti-hallucination'],
  installedStandards: ['anti-hallucination', 'commit-message'],
  contentMode: 'index',
  language: 'en',
  standardsFormat: 'ai',
  outputLanguage: 'english'
};

describe('P2-b: an existing integration file loses its dead links too', () => {
  beforeEach(() => {
    rmSync(TEST_DIR, { recursive: true, force: true });
    mkdirSync(join(TEST_DIR, '.standards'), { recursive: true });
    writeFileSync(join(TEST_DIR, '.standards/anti-hallucination.ai.yaml'), 'id: anti-hallucination\n');
    writeFileSync(join(TEST_DIR, '.standards/commit-message.ai.yaml'), 'id: commit-message\n');
    // A file written by an older CLI: dead links, and user content that must survive.
    writeFileSync(join(TEST_DIR, 'CLAUDE.md'), [
      '# Project Guidelines',
      '',
      '## Anti-Hallucination',
      'Reference: .standards/anti-hallucination.md',
      '',
      '## Commit',
      'Reference: .standards/commit-message-guide.md',
      '',
      '## My own notes',
      'Keep this line exactly as it is.',
      ''
    ].join('\n'));
  });
  afterEach(() => rmSync(TEST_DIR, { recursive: true, force: true }));

  it('rewrites stale paths and keeps user content', () => {
    const result = writeIntegrationFile('claude-code', config, TEST_DIR);
    expect(result.success).toBe(true);

    const content = readFileSync(join(TEST_DIR, 'CLAUDE.md'), 'utf-8');

    expect(content).not.toMatch(/\.standards\/anti-hallucination\.md/);
    expect(content).not.toMatch(/\.standards\/commit-message-guide\.md/);
    expect(content).toMatch(/\.standards\/anti-hallucination\.ai\.yaml/);
    expect(content).toContain('Keep this line exactly as it is.');
  });
  it('leaves alone a reference the project added itself, when the file is there', () => {
    // 🔴 The first version of this fix dropped every reference whose stem was not
    // an installed standard — including `.standards/our-house-rule.md`, a file
    // the project put there on purpose. Deleting a user's own line is worse than
    // the dead link this change set out to remove.
    writeFileSync(join(TEST_DIR, '.standards/our-house-rule.md'), 'house rule\n');
    writeFileSync(join(TEST_DIR, 'CLAUDE.md'), [
      '# Project Guidelines',
      '',
      '## Ours',
      'Reference: .standards/our-house-rule.md',
      '',
      '## Theirs',
      'Reference: .standards/anti-hallucination.md',
      ''
    ].join('\n'));

    writeIntegrationFile('claude-code', config, TEST_DIR);
    const content = readFileSync(join(TEST_DIR, 'CLAUDE.md'), 'utf-8');

    expect(content).toMatch(/\.standards\/our-house-rule\.md/);
    expect(content).not.toMatch(/\.standards\/anti-hallucination\.md/);
  });

  it('drops a UDS standard this project never installed', () => {
    writeFileSync(join(TEST_DIR, 'CLAUDE.md'), [
      '# Project Guidelines',
      '',
      '## Review',
      'Reference: .standards/checkin-standards.md',
      ''
    ].join('\n'));

    writeIntegrationFile('claude-code', config, TEST_DIR);
    const content = readFileSync(join(TEST_DIR, 'CLAUDE.md'), 'utf-8');

    expect(content).not.toMatch(/\.standards\/checkin-standards/);
  });
});
