/**
 * uninstall — completeness, and the rule that bounds it.
 *
 * Adopter report (6.14.0-beta.2): after `init` → `update --with-hooks` →
 * `uninstall -y`, the run said "Removed 5, Skipped 1, Errors 0" and left behind
 *   a) 15 UDS-written files under scripts/hooks/,
 *   b) an empty `.codex/` folder (its hooks.json was UDS's, and was deleted),
 *   c) AGENTS.md — "UDS block removed, keep user content" — although the whole
 *      file was generated by UDS and now points at a `.standards/` that is gone,
 *   d) .git/hooks/pre-commit — three UDS lines removed, the rest of the script
 *      it had written (header, linter fallbacks, "checks passed" echo) kept.
 *
 * The rule the fix follows (decided by the maintainer, asserted below): delete
 * only what UDS can PROVE it wrote and that nobody has changed since — a record
 * in the manifest plus a matching content hash. No record, or a changed hash:
 * keep it, and say why. The adopter's own files are asserted to survive.
 *
 * These tests drive the real installers to produce the on-disk state and the
 * manifest records, then the real uninstall command — a hand-built manifest would
 * only prove that the uninstaller agrees with the test author.
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import {
  existsSync, mkdirSync, writeFileSync, readFileSync, rmSync, readdirSync, statSync
} from 'fs';
import { join, relative } from 'path';
import { tmpdir } from 'os';

import { uninstallCommand } from '../../../src/commands/uninstall.js';
import { uninstallHook, pruneCreatedDirs } from '../../../src/uninstallers/hook-uninstaller.js';
import { uninstallIntegrations } from '../../../src/uninstallers/integration-uninstaller.js';
import { installMissingHooks, installHooks } from '../../../src/installers/hooks-installer.js';
import { writeAgentsMdSummary } from '../../../src/utils/integration-generator.js';
import {
  newRecorder, recordFile, persistRecorder, RECORD_KINDS, RECORDS_KEY
} from '../../../src/core/install-records.js';
import { readManifest } from '../../../src/core/manifest.js';
import { setupHuskyHook } from '../../../src/commands/init.js';

/** Every file and directory under `dir`, as forward-slash relative paths. */
function snapshot(dir) {
  const out = [];
  const walk = (d) => {
    for (const e of readdirSync(d, { withFileTypes: true })) {
      const abs = join(d, e.name);
      out.push(relative(dir, abs).replace(/\\/g, '/'));
      if (e.isDirectory()) walk(abs);
    }
  };
  walk(dir);
  return out.filter((p) => p !== '.git' && !p.startsWith('.git/') || p.startsWith('.git/hooks/pre-commit')).sort();
}

describe('uninstall completeness', () => {
  let dir;
  let originalCwd;
  let out;

  const printed = () => out.mock.calls.map((c) => c.join(' ')).join('\n');
  const read = (rel) => readFileSync(join(dir, rel), 'utf-8');
  const exists = (rel) => existsSync(join(dir, rel));

  function writeManifest(extra = {}) {
    mkdirSync(join(dir, '.standards'), { recursive: true });
    writeFileSync(join(dir, '.standards', 'commit-message.ai.yaml'), 'content');
    writeFileSync(join(dir, '.standards', 'manifest.json'), JSON.stringify({
      version: '3.4.0',
      upstream: { repo: 'test', version: '1.0.0', installed: new Date().toISOString() },
      format: 'ai', contentMode: 'index', standards: ['commit-message'], extensions: [],
      integrations: [], integrationConfigs: {}, options: {}, aiTools: [],
      skills: { installed: false, location: 'project', names: [], version: null, installations: [] },
      commands: { installed: false, names: [], version: null, installations: [] },
      methodology: null, fileHashes: {}, skillHashes: {}, commandHashes: {}, integrationBlockHashes: {},
      ...extra
    }, null, 2));
  }

  /** What `uds update --with-hooks` does, including recording it. */
  function installHooksLikeUpdate(tools) {
    const { artifacts } = installMissingHooks(dir, tools, { plan: false, overwriteScripts: false });
    persistRecorder(dir, artifacts);
  }

  /** Same manifest with the install records removed — what an install by an older UDS looks like. */
  function dropRecords() {
    const p = join(dir, '.standards', 'manifest.json');
    const m = JSON.parse(readFileSync(p, 'utf-8'));
    delete m[RECORDS_KEY];
    writeFileSync(p, JSON.stringify(m, null, 2));
  }

  beforeEach(() => {
    dir = join(tmpdir(), `uds-test-uninstall-complete-${Date.now()}-${Math.random().toString(36).slice(2)}`);
    mkdirSync(join(dir, '.git', 'hooks'), { recursive: true });
    originalCwd = process.cwd();
    process.chdir(dir);
    process.exitCode = undefined;
    out = vi.spyOn(console, 'log').mockImplementation(() => {});
  });

  afterEach(() => {
    process.chdir(originalCwd);
    process.exitCode = undefined;
    rmSync(dir, { recursive: true, force: true });
    vi.restoreAllMocks();
  });

  // ─────────────────────────────────────────────────────────────────────────
  describe('hook scripts and the folders UDS created (a, b)', () => {
    it('removes every script UDS wrote and the folders it created, keeping the adopter\'s files', async () => {
      // The adopter's own file, in a directory UDS's hook config also uses.
      mkdirSync(join(dir, '.agents', 'rules'), { recursive: true });
      writeFileSync(join(dir, '.agents', 'rules', 'style.md'), '# my style\n');
      writeManifest();
      installHooksLikeUpdate(['codex', 'antigravity']);
      expect(exists('.codex/hooks.json')).toBe(true);
      expect(readdirSync(join(dir, 'scripts', 'hooks')).length).toBeGreaterThan(5);

      await uninstallCommand({ all: true, yes: true });

      expect(exists('scripts')).toBe(false);          // all of scripts/hooks was UDS's, and so was scripts/
      expect(exists('.codex')).toBe(false);           // the emptied folder (b)
      expect(exists('.agents/hooks.json')).toBe(false);
      // The adopter's file, and therefore the folder that holds it, stay.
      expect(read('.agents/rules/style.md')).toBe('# my style\n');
      expect(exists('.agents')).toBe(true);
      expect(process.exitCode ?? 0).toBe(0);
    });

    it('keeps an adopter script that lives beside UDS\'s, and the folder that holds it', async () => {
      writeManifest();
      installHooksLikeUpdate(['codex']);
      writeFileSync(join(dir, 'scripts', 'hooks', 'my-own-hook.mjs'), '// mine\n');

      await uninstallCommand({ all: true, yes: true });

      expect(read('scripts/hooks/my-own-hook.mjs')).toBe('// mine\n');
      expect(exists('scripts/hooks/check-turn-completion-codex.mjs')).toBe(false);
      expect(exists('scripts/hooks/turn-completion')).toBe(false); // UDS's sub-folder, emptied
      expect(printed()).toMatch(/scripts\/hooks\/ \(kept: created by UDS but not empty/);
    });

    it('keeps a UDS script the adopter edited, and says it was modified', async () => {
      writeManifest();
      installHooksLikeUpdate(['codex']);
      writeFileSync(join(dir, 'scripts', 'hooks', 'validate-commit-msg.mjs'), '// I changed this\n');

      await uninstallCommand({ all: true, yes: true });

      expect(read('scripts/hooks/validate-commit-msg.mjs')).toBe('// I changed this\n');
      expect(printed()).toMatch(/validate-commit-msg\.mjs \(kept: modified since UDS wrote it\)/);
      expect(exists('scripts/hooks/check-turn-completion-codex.mjs')).toBe(false);
    });

    it('an install from before records existed is kept and explained, never guessed at', async () => {
      writeManifest();
      installHooksLikeUpdate(['codex']);
      dropRecords();
      const before = snapshot(dir).filter((p) => p.startsWith('scripts/'));

      await uninstallCommand({ all: true, yes: true });

      // Not one script deleted, and the folders (not recorded either) stay.
      expect(snapshot(dir).filter((p) => p.startsWith('scripts/'))).toEqual(before);
      expect(exists('.codex')).toBe(true);
      expect(printed()).toMatch(/scripts\/hooks\/ \(kept: \d+ files carry the name of a UDS hook script, but the manifest has no record/);
      // The config entry that ran those scripts is still removed.
      expect(exists('.codex/hooks.json')).toBe(false);
    });

    it('does not delete a script while a hook config that runs it could not be cleaned', () => {
      writeManifest();
      installHooksLikeUpdate(['codex']);
      writeFileSync(join(dir, '.codex', 'hooks.json'), '{ not json');
      const manifest = readManifest(dir);

      const result = uninstallHook(dir, { manifest });

      expect(result.errors.join('\n')).toContain('.codex/hooks.json');
      expect(exists('scripts/hooks/check-turn-completion-codex.mjs')).toBe(true);
      expect(result.skipped.join('\n')).toContain('kept: a hook config file could not be cleaned');
    });

    it('the reported set of deletions is exactly the set that disappeared', () => {
      mkdirSync(join(dir, '.agents', 'rules'), { recursive: true });
      writeFileSync(join(dir, '.agents', 'rules', 'style.md'), 'x');
      writeManifest();
      installHooksLikeUpdate(['codex', 'antigravity', 'claude-code']);
      const manifest = readManifest(dir);
      const before = snapshot(dir);

      const hooks = uninstallHook(dir, { manifest });
      const folders = pruneCreatedDirs(dir, manifest);
      const after = snapshot(dir);

      const disappeared = before.filter((p) => !after.includes(p));
      const claimed = [...hooks.deletedPaths, ...folders.deletedPaths];
      expect([...new Set(claimed)].sort()).toEqual(disappeared.sort());
      // and each claimed deletion is one line in `removed` (no double counting, no silent ones)
      expect(hooks.removed.length + folders.removed.length).toBeGreaterThanOrEqual(claimed.length);
      expect(hooks.errors).toEqual([]);
    });

    it('"Removed: N" printed at the end equals the number of ✓ lines printed', async () => {
      writeManifest();
      installHooksLikeUpdate(['codex', 'antigravity']);

      await uninstallCommand({ all: true, yes: true });

      const text = printed();
      const m = text.match(/Removed: (\d+)\s+Skipped: (\d+)\s+Errors: (\d+)/);
      expect(m).not.toBeNull();
      const ticks = text.split('\n').filter((l) => /^\s*✓ /.test(l) && !/Uninstall complete/.test(l));
      // The preview block prints "✓ Remove: ..." once per item, the results block "✓ ..." once per item.
      const previewLines = ticks.filter((l) => /✓ Remove:/.test(l)).length;
      const resultLines = ticks.length - previewLines;
      expect(Number(m[1])).toBe(resultLines);
      expect(previewLines).toBe(resultLines);
      expect(Number(m[3])).toBe(0);
    });

    it('--dry-run reports the same deletions and changes nothing', async () => {
      mkdirSync(join(dir, '.agents', 'rules'), { recursive: true });
      writeFileSync(join(dir, '.agents', 'rules', 'style.md'), 'x');
      writeManifest();
      installHooksLikeUpdate(['codex', 'antigravity']);
      const before = snapshot(dir);

      await uninstallCommand({ dryRun: true });

      expect(snapshot(dir)).toEqual(before);
      const text = printed();
      expect(text).toContain('scripts/hooks/check-turn-completion.mjs');
      expect(text).toContain('.codex/ (empty folder created by UDS, removed)');
      // `.agents/` existed before UDS touched anything, so it is not UDS's to remove or to
      // mention as "kept because not empty" — only folders UDS created are ever considered.
      expect(text).not.toMatch(/\.agents\/ \(/);
    });
  });

  // ─────────────────────────────────────────────────────────────────────────
  describe('AGENTS.md generated by UDS (c)', () => {
    const summaryConfig = { installedStandards: ['commit-message'], language: 'en', outputLanguage: 'english', standardOptions: {} };

    function createAgentsMdLikeInit({ record }) {
      const r = writeAgentsMdSummary(summaryConfig, dir);
      expect(r.created).toBe(true);
      writeManifest({ integrations: ['AGENTS.md'], generateAgentsMd: true });
      if (record) {
        const rec = newRecorder();
        recordFile(rec, dir, 'AGENTS.md', RECORD_KINDS.INTEGRATION_FILE);
        persistRecorder(dir, rec);
      }
    }

    it('deletes the whole file when UDS created it and only its own text is outside the block', async () => {
      createAgentsMdLikeInit({ record: true });
      expect(read('AGENTS.md')).toContain('Auto-generated by');

      await uninstallCommand({ all: true, yes: true });

      expect(exists('AGENTS.md')).toBe(false);
    });

    it('still deletes it after `uds update` rewrote the block (only the block changed)', async () => {
      createAgentsMdLikeInit({ record: true });
      const r = writeAgentsMdSummary({ ...summaryConfig, installedStandards: ['commit-message', 'testing'] }, dir);
      expect(r.created).toBe(false);

      await uninstallCommand({ all: true, yes: true });

      expect(exists('AGENTS.md')).toBe(false);
    });

    it('keeps text the adopter added, removes the block, and says why the rest stayed', async () => {
      createAgentsMdLikeInit({ record: true });
      writeFileSync(join(dir, 'AGENTS.md'), read('AGENTS.md') + '\n## Team notes\n\nDeploy on Fridays. Never.\n');

      await uninstallCommand({ all: true, yes: true });

      expect(exists('AGENTS.md')).toBe(true);
      const left = read('AGENTS.md');
      expect(left).toContain('Deploy on Fridays. Never.');
      expect(left).not.toContain('UDS:STANDARDS:START');
      expect(printed()).toMatch(/AGENTS\.md \(kept: the text outside the UDS block — modified since UDS wrote it\)/);
    });

    it('a file from before records existed keeps its outside text and says there is no record', async () => {
      createAgentsMdLikeInit({ record: false });

      await uninstallCommand({ all: true, yes: true });

      expect(exists('AGENTS.md')).toBe(true);
      expect(read('AGENTS.md')).not.toContain('UDS:STANDARDS:START');
      expect(printed()).toMatch(/AGENTS\.md \(kept: the text outside the UDS block — no install record/);
    });

    it('a file the adopter already had is never recorded as UDS\'s, so their text always survives', async () => {
      writeFileSync(join(dir, 'AGENTS.md'), '# Our agents\n\nBe kind.\n');
      const r = writeAgentsMdSummary(summaryConfig, dir);
      expect(r.created).toBe(false);
      writeManifest({ integrations: ['AGENTS.md'], generateAgentsMd: true });

      await uninstallCommand({ all: true, yes: true });

      expect(read('AGENTS.md')).toContain('Be kind.');
      expect(read('AGENTS.md')).not.toContain('UDS:STANDARDS:START');
    });

    it('a partial uninstall forgets the record of the file it deleted, so a later file at that path proves nothing', async () => {
      createAgentsMdLikeInit({ record: true });
      expect(JSON.parse(read('.standards/manifest.json'))[RECORDS_KEY].files['AGENTS.md']).toBeDefined();

      await uninstallCommand({ integrationsOnly: true, yes: true });

      expect(exists('AGENTS.md')).toBe(false);
      expect(exists('.standards/manifest.json')).toBe(true);
      expect(JSON.parse(read('.standards/manifest.json'))[RECORDS_KEY].files['AGENTS.md']).toBeUndefined();
    });

    it('preview says "delete file" only when the deletion is provable', async () => {
      createAgentsMdLikeInit({ record: true });
      const manifest = readManifest(dir);
      const proven = await uninstallIntegrations(dir, manifest, { dryRun: true });
      expect(proven.removed.join('\n')).toContain('AGENTS.md (delete file');

      dropRecords();
      const unproven = await uninstallIntegrations(dir, readManifest(dir), { dryRun: true });
      expect(unproven.removed.join('\n')).toContain('remove UDS block, keep user content');
      expect(unproven.skipped.join('\n')).toContain('no install record');
    });
  });

  // ─────────────────────────────────────────────────────────────────────────
  describe('the native .git/hooks/pre-commit script (d)', () => {
    async function installNative() {
      writeManifest();
      await setupHuskyHook(dir, { allowInTest: true });
      expect(read('.git/hooks/pre-commit')).toContain('Auto-generated by uds init');
    }

    it('deletes the whole script UDS wrote, not just the lines that match a pattern', async () => {
      await installNative();

      await uninstallCommand({ all: true, yes: true });

      expect(exists('.git/hooks/pre-commit')).toBe(false);
    });

    it('a script the adopter edited loses only its UDS lines, and the rest is reported as kept', async () => {
      await installNative();
      writeFileSync(join(dir, '.git', 'hooks', 'pre-commit'), read('.git/hooks/pre-commit') + '\nmake lint\n');

      await uninstallCommand({ all: true, yes: true });

      const left = read('.git/hooks/pre-commit');
      expect(left).toContain('make lint');
      expect(left).not.toMatch(/uds check/);
      expect(printed()).toMatch(/\.git\/hooks\/pre-commit \(kept: the rest of the script — modified since UDS wrote it\)/);
    });

    it('a script from before records existed is kept and explained', async () => {
      await installNative();
      dropRecords();

      await uninstallCommand({ all: true, yes: true });

      expect(exists('.git/hooks/pre-commit')).toBe(true);
      expect(printed()).toMatch(/\.git\/hooks\/pre-commit \(kept: the rest of the script — no install record/);
    });

    it('an adopter\'s own pre-commit hook, which UDS never wrote, is not deleted', async () => {
      writeManifest();
      writeFileSync(join(dir, '.git', 'hooks', 'pre-commit'), '#!/bin/sh\nnpm test\n');

      await uninstallCommand({ all: true, yes: true });

      expect(read('.git/hooks/pre-commit')).toBe('#!/bin/sh\nnpm test\n');
    });
  });

  // ─────────────────────────────────────────────────────────────────────────
  describe('the husky pre-commit file', () => {
    function nodeProject() {
      writeFileSync(join(dir, 'package.json'), JSON.stringify({ name: 'x', version: '1.0.0', devDependencies: { husky: '^9.1.7' } }));
    }

    it('deletes a file UDS created and the .husky folder it had to make', async () => {
      nodeProject();
      writeManifest();
      await setupHuskyHook(dir, { allowInTest: true });
      expect(read('.husky/pre-commit')).toContain('uds check');

      await uninstallCommand({ all: true, yes: true });

      expect(exists('.husky')).toBe(false);
    });

    it('a hook file the adopter already had only loses the UDS lines', async () => {
      nodeProject();
      mkdirSync(join(dir, '.husky'), { recursive: true });
      writeFileSync(join(dir, '.husky', 'pre-commit'), '#!/bin/sh\nnpm run lint\n');
      writeManifest();
      await setupHuskyHook(dir, { allowInTest: true });

      await uninstallCommand({ all: true, yes: true });

      expect(read('.husky/pre-commit')).toContain('npm run lint');
      expect(read('.husky/pre-commit')).not.toContain('uds check');
    });
  });

  // ─────────────────────────────────────────────────────────────────────────
  describe('the recording side', () => {
    it('installHooks records only the files and folders it actually created', () => {
      // `.claude/` and one script already exist and are the adopter's.
      mkdirSync(join(dir, '.claude'), { recursive: true });
      mkdirSync(join(dir, 'scripts', 'hooks'), { recursive: true });
      writeFileSync(join(dir, 'scripts', 'hooks', 'validate-commit-msg.mjs'), '// adopter version\n');

      const result = installHooks(dir, { overwriteScripts: false });
      const files = Object.keys(result.artifacts.files);

      expect(files).not.toContain('scripts/hooks/validate-commit-msg.mjs'); // existed, kept, not ours
      expect(files).toContain('scripts/hooks/check-turn-completion.mjs');
      expect(result.artifacts.createdDirs).not.toContain('.claude');
      expect(result.artifacts.createdDirs).not.toContain('scripts');
      expect(result.artifacts.createdDirs).not.toContain('scripts/hooks');
      expect(result.artifacts.createdDirs).toContain('scripts/hooks/turn-completion');
      expect(statSync(join(dir, 'scripts', 'hooks', 'check-turn-completion.mjs')).isFile()).toBe(true);
    });
  });
});
