#!/usr/bin/env bash
# check-flow-gate-report.sh
# Verifies that flow_gate_report.json exists and has valid summary.status.
# Part of UDS Release Readiness Gate (core/release-readiness-gate.md, Dimension 16).
#
# In CI, this file is generated by scripts/generate-flow-gate-report.mjs after
# all Decision Table tests pass (Gate 3). It feeds into release-quality-manifest.yaml.
#
# Exit codes:
#   0 — report found, summary.status is "pass"
#   1 — report missing, malformed, or summary.status is not "pass" (advisory)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPORT_FILE="$REPO_ROOT/flow_gate_report.json"

# Check if report exists
if [ ! -f "$REPORT_FILE" ]; then
    echo "⚠ flow_gate_report.json not found at repo root."
    echo "  This file is generated after Gate 3 (Pre-UAT CI) completes."
    echo "  If no flows have ≥3 steps, create a minimal report:"
    echo '  {"generated_at":"...","commit":"...","flows":[],"summary":{"total_flows":0,"gate_0_complete":true,"gate_1_pr_coverage":true,"gate_3_ci_pass":true,"gate_4_uat_signoff":true,"status":"pass"}}'
    exit 1
fi

# Validate JSON and check summary.status (requires jq or node)
if command -v jq &>/dev/null; then
    status=$(jq -r '.summary.status // "missing"' "$REPORT_FILE")
else
    status=$(node -e "
      const r = JSON.parse(require('fs').readFileSync('$REPORT_FILE'));
      console.log(r.summary && r.summary.status ? r.summary.status : 'missing');
    " 2>/dev/null || echo "parse_error")
fi

case "$status" in
    "pass")
        total=$(jq -r '.summary.total_flows // 0' "$REPORT_FILE" 2>/dev/null || echo "?")
        echo "✓ flow_gate_report.json: summary.status=pass ($total flows)"
        exit 0
        ;;
    "warn")
        echo "⚠ flow_gate_report.json: summary.status=warn"
        echo "  Check individual flow gate_3 entries for non-passing flows."
        exit 1
        ;;
    "fail")
        echo "✗ flow_gate_report.json: summary.status=fail"
        echo "  Gate 3 CI has failing Decision Table scenarios."
        echo "  Fix all terminal state coverage issues before Pre-UAT deployment."
        exit 1
        ;;
    "missing"|"parse_error")
        echo "⚠ flow_gate_report.json is malformed or missing summary.status field."
        echo "  Expected schema: see core/flow-based-testing.md §RQM Integration"
        exit 1
        ;;
    *)
        echo "⚠ flow_gate_report.json: unknown status '$status'"
        exit 1
        ;;
esac
