/**
 * Which files are code, which are tests, and which UDS cannot tell — one answer,
 * configurable per project. // implements XSPEC-444 R2 (and the classification R5's scripts share)
 *
 * Why this is data and not a branch per language: UDS is a general standard, and the
 * check built on this must work in every language an adopter writes. So "what is a test
 * file" is a list of path patterns with defaults for the common ecosystems, and a project
 * adds its own in `.standards/test-policy.json`. No test framework is named anywhere.
 *
 * Three answers beyond "code" and "test", and the third is the point:
 *   - `noncode`      docs, data, config, images — known not to need a test
 *   - `ignored`      generated/vendored/tooling paths (node_modules, dist, .github, ...)
 *   - `unclassified` an extension this table has never heard of. It is NOT assumed to be
 *                    code and it is NOT assumed to be safe: the caller must say so out
 *                    loud. A language UDS does not know must not read as "passed".
 *
 * The same defaults are copied into the two gate scripts UDS ships to adopters
 * (templates/gates/check-anti-fake-tests.mjs, check-stubs.mjs) because those run in a
 * project with no UDS code beside them. A test (test-policy-drift) compares all three.
 *
 * Policy file `.standards/test-policy.json` (optional; every list ADDS to the defaults):
 *   {
 *     "mode": "warn" | "block",                 // default "warn"
 *     "testDirs": ["integration"],               // directory names that hold tests
 *     "testPatterns": ["*.itest.*"],             // file-name globs of test files
 *     "sourceExtensions": ["zig"],               // extensions that are code
 *     "nonCodeExtensions": ["gradle"],           // extensions that are not
 *     "ignore": ["generated/**"],                // path globs to leave alone
 *     "exempt": [{ "pattern": "src/gen/**", "reason": "generated by protoc" }]
 *   }
 * An `exempt` entry without a `reason` is not honored (and is reported): an exemption that
 * leaves no explanation is just a switch.
 */

import { existsSync, readFileSync } from 'fs';
import { join } from 'path';

// ---- BEGIN SHARED POLICY (identical in templates/gates/check-anti-fake-tests.mjs and check-stubs.mjs; test-policy-drift.test.js compares them) ----
/** Where an adopter's policy lives (inside `.standards/`, beside release-config.yaml). */
export const POLICY_FILE = '.standards/test-policy.json';

export const DEFAULT_POLICY = Object.freeze({
  mode: 'warn',
  testDirs: Object.freeze(['test', 'tests', '__tests__', 'spec', 'e2e']),
  testPatterns: Object.freeze([
    '*.test.*', '*.spec.*', '*_test.*', '*_spec.*', 'test_*.*', 'conftest.py',
    '*Test.*', '*Tests.*', '*Spec.scala', '*Spec.kt', '*Spec.groovy'
  ]),
  sourceExtensions: Object.freeze([
    'js', 'mjs', 'cjs', 'jsx', 'ts', 'tsx', 'mts', 'cts', 'vue', 'svelte', 'astro',
    'py', 'pyi', 'java', 'kt', 'kts', 'scala', 'groovy', 'go', 'rs', 'rb', 'php', 'cs', 'fs', 'vb',
    'swift', 'm', 'mm', 'dart', 'c', 'h', 'cc', 'cpp', 'cxx', 'hpp', 'hh',
    'ex', 'exs', 'erl', 'hrl', 'lua', 'pl', 'pm', 'r', 'jl', 'clj', 'cljs', 'hs', 'ml', 'mli',
    'sh', 'bash', 'zsh', 'ps1'
  ]),
  nonCodeExtensions: Object.freeze([
    'md', 'mdx', 'txt', 'rst', 'adoc', 'json', 'jsonc', 'json5', 'yaml', 'yml', 'toml', 'ini', 'cfg',
    'conf', 'properties', 'env', 'lock', 'xml', 'csv', 'tsv', 'svg', 'png', 'jpg', 'jpeg', 'gif', 'ico',
    'webp', 'avif', 'pdf', 'woff', 'woff2', 'ttf', 'otf', 'eot', 'map', 'html', 'htm', 'css', 'scss',
    'sass', 'less', 'sql', 'gitignore', 'gitattributes', 'editorconfig', 'npmrc', 'nvmrc', 'license',
    'log', 'snap'
  ]),
  nonCodeNames: Object.freeze([
    'LICENSE', 'README', 'CHANGELOG', 'NOTICE', 'AUTHORS', 'CODEOWNERS', 'Dockerfile', 'Makefile', 'Procfile'
  ]),
  ignoreDirs: Object.freeze([
    'node_modules', 'vendor', 'dist', 'build', 'coverage', '.git', '.standards', '.claude', '.husky',
    '.github', 'docs', 'target', '__pycache__', '.venv', 'venv', '.next', '.nuxt', '.idea', '.vscode',
    '.ruff_cache', '.pytest_cache', '.mypy_cache', '.tox', '.gradle', '.cache', '.turbo', '.svelte-kit',
    '.parcel-cache', '.terraform', '.dart_tool', '.eggs'
  ]),
  ignore: Object.freeze(['**/*.min.js', '**/*.min.css', '**/*.d.ts']),
  exempt: Object.freeze([])
});

const norm = (p) => String(p).replace(/\\/g, '/').replace(/^\.\//, '');

/** Glob → RegExp. `*` stays inside a path segment, `**` crosses them, `?` is one non-slash character. */
export function globToRegex(glob) {
  const g = norm(glob);
  let re = '';
  for (let i = 0; i < g.length; i++) {
    const c = g[i];
    if (c === '*') {
      if (g[i + 1] === '*') {
        if (g[i + 2] === '/') { re += '(?:.*/)?'; i += 2; } else { re += '.*'; i += 1; }
      } else {
        re += '[^/]*';
      }
    } else if (c === '?') {
      re += '[^/]';
    } else if ('\\^$+.()|{}[]'.includes(c)) {
      re += '\\' + c;
    } else {
      re += c;
    }
  }
  return new RegExp(`^${re}$`);
}

/** A glob with no slash is a file-name glob (matches the basename anywhere); otherwise it matches the whole path. */
function matchesGlob(relPath, glob) {
  const p = norm(relPath);
  const g = norm(glob);
  const target = g.includes('/') ? p : p.split('/').pop();
  return globToRegex(g).test(target);
}

const extOf = (relPath) => {
  const base = norm(relPath).split('/').pop();
  const i = base.lastIndexOf('.');
  return i > 0 ? base.slice(i + 1).toLowerCase() : '';
};

/**
 * Read `.standards/test-policy.json` and merge it over the defaults.
 * @returns {{ policy: object, problems: string[], source: string|null }}
 *   `problems` is never swallowed: an unreadable file or a bad value is reported, and the
 *   defaults (mode "warn") are what runs.
 */
export function loadPolicy(projectPath) {
  const problems = [];
  const policy = {
    mode: DEFAULT_POLICY.mode,
    testDirs: [...DEFAULT_POLICY.testDirs],
    testPatterns: [...DEFAULT_POLICY.testPatterns],
    sourceExtensions: [...DEFAULT_POLICY.sourceExtensions],
    nonCodeExtensions: [...DEFAULT_POLICY.nonCodeExtensions],
    nonCodeNames: [...DEFAULT_POLICY.nonCodeNames],
    ignoreDirs: [...DEFAULT_POLICY.ignoreDirs],
    ignore: [...DEFAULT_POLICY.ignore],
    exempt: []
  };
  const file = join(projectPath, POLICY_FILE);
  if (!existsSync(file)) return { policy, problems, source: null };

  let raw;
  try {
    raw = JSON.parse(readFileSync(file, 'utf-8').replace(/^\uFEFF/, ''));
  } catch (e) {
    problems.push(`${POLICY_FILE} cannot be read (${e.message}); defaults are in effect`);
    return { policy, problems, source: POLICY_FILE };
  }
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) {
    problems.push(`${POLICY_FILE} must be a JSON object; defaults are in effect`);
    return { policy, problems, source: POLICY_FILE };
  }

  if (raw.mode !== undefined) {
    if (raw.mode === 'warn' || raw.mode === 'block') policy.mode = raw.mode;
    else problems.push(`${POLICY_FILE}: "mode" must be "warn" or "block", got ${JSON.stringify(raw.mode)}; "warn" is in effect`);
  }
  for (const key of ['testDirs', 'testPatterns', 'sourceExtensions', 'nonCodeExtensions', 'ignore']) {
    if (raw[key] === undefined) continue;
    if (!Array.isArray(raw[key]) || raw[key].some((v) => typeof v !== 'string' || !v)) {
      problems.push(`${POLICY_FILE}: "${key}" must be an array of non-empty strings; it is ignored`);
      continue;
    }
    const add = key === 'sourceExtensions' || key === 'nonCodeExtensions'
      ? raw[key].map((v) => v.replace(/^\./, '').toLowerCase())
      : raw[key];
    policy[key] = [...policy[key], ...add];
  }
  if (raw.exempt !== undefined) {
    if (!Array.isArray(raw.exempt)) {
      problems.push(`${POLICY_FILE}: "exempt" must be an array; it is ignored`);
    } else {
      raw.exempt.forEach((e, i) => {
        const okPattern = e && typeof e.pattern === 'string' && e.pattern.trim();
        const okReason = e && typeof e.reason === 'string' && e.reason.trim();
        if (!okPattern) problems.push(`${POLICY_FILE}: exempt[${i}] has no "pattern"; it is ignored`);
        else if (!okReason) problems.push(`${POLICY_FILE}: exempt[${i}] ("${e.pattern}") has no "reason" and is NOT honored — an exemption must say why`);
        else policy.exempt.push({ pattern: e.pattern, reason: e.reason.trim() });
      });
    }
  }
  return { policy, problems, source: POLICY_FILE };
}

/**
 * Classify one project-relative path.
 * @returns {{ kind: 'ignored'|'noncode'|'test'|'source'|'unclassified', ext: string, exempt?: {pattern:string, reason:string} }}
 */
export function classifyPath(relPath, policy = DEFAULT_POLICY) {
  const p = norm(relPath);
  const segments = p.split('/');
  const base = segments[segments.length - 1];
  const dirs = segments.slice(0, -1);
  const ext = extOf(p);
  const sets = {
    source: new Set(policy.sourceExtensions || DEFAULT_POLICY.sourceExtensions),
    noncode: new Set(policy.nonCodeExtensions || DEFAULT_POLICY.nonCodeExtensions),
    names: new Set(policy.nonCodeNames || DEFAULT_POLICY.nonCodeNames),
    ignoreDirs: new Set(policy.ignoreDirs || DEFAULT_POLICY.ignoreDirs)
  };

  if (dirs.some((d) => sets.ignoreDirs.has(d))) return { kind: 'ignored', ext };
  if ((policy.ignore || DEFAULT_POLICY.ignore).some((g) => matchesGlob(p, g))) return { kind: 'ignored', ext };

  const docsLike = sets.noncode.has(ext) || sets.names.has(base) || sets.names.has(base.replace(/\.[^.]*$/, ''));
  const inTestDir = dirs.some((d) => (policy.testDirs || DEFAULT_POLICY.testDirs).includes(d));
  const testNamed = (policy.testPatterns || DEFAULT_POLICY.testPatterns).some((g) => matchesGlob(p, g));

  // A test is a test even when its data is JSON; but a README inside tests/ is documentation.
  if ((inTestDir || testNamed) && !['md', 'mdx', 'txt', 'rst', 'adoc'].includes(ext)) return { kind: 'test', ext };
  // Dot-files (.prettierrc, .eslintrc.js, .env.local ...) are tool configuration, not product code.
  if (docsLike || base.startsWith('.')) return { kind: 'noncode', ext };
  if (sets.source.has(ext)) {
    const exempt = (policy.exempt || []).find((e) => matchesGlob(p, e.pattern));
    return exempt ? { kind: 'source', ext, exempt } : { kind: 'source', ext };
  }
  return { kind: 'unclassified', ext };
}
// ---- END SHARED POLICY ----
